config/routes.rb
Website::Application.routes.draw do
  
  get "games/index"

  match "/home", :to => "home#index"
  match "/games", :to => "games#index"
  
  root :to => "home#index"
    
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  
  resources :message
  
end

app/models/message.rb
class Message
  
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    respond_to do |format|    
      if @message.valid? and verify_recaptcha(:model => @message, 
          :message => "Please re-enter the words from the image again!")
        Notifier.new_message(@message).deliver
        flash[:notice] = "Message was sent successfully"
        format.html { redirect_to root_path }
        format.js 
      else
        flash[:notice] = "There were errors sending your message."
        format.html { render :action => "new" }
        format.js  {
            render :template=>"contact/create.js.erb", 
            :locals=>{ :item => @message, :notice => 'There were errors sending your message.'
            }}
      end
    end

  end
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def facebook_like
    content_tag :iframe, nil, 
      :src => "http://www.facebook.com/plugins/like.php?app_id=141440452603597&href=#{CGI::escape(request.url)}&send=false&layout=box_count&show_faces=false&action=like&font=arial&colorscheme=light&locale=en_US",
      :scrolling => 'no', :frameborder => '0', :allowtransparency => true, :id => :facebook_like, :width => '100%'
  end
  

 
  def build_link
    link_to "eddie.heroku.com", "http://eddie.heroku.com" 
  end
  
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  
  def gravatar_for(user, options = { :size => 50})
    #gravatar_image_tag(user.email.downcase, :alt => user.name,
    #                                        :class => 'gravatar',
    #                                        :gravatar => options)

  end
  
  def gravatar_for(email, options = { :size => 50})
    gravatar_image_tag(email.downcase, :alt => "gravatar_img", :class => 'gravatar')
  end
  
end

app/views/contact/_form.html.erb
<h2>Fill out the form below and I will try to reply as soon as possible. Thanks.</h2>
<%= form_for @message, :url => contact_path, :remote => true do |form| %>
<div class="err_msgs">
</div>
	<label class="input">
		<span style="color: rgb(0, 0, 0); ">Name</span>
		<%= form.text_field :name %>
	</label>
	<label class="input"> 
		<span style="color: rgb(0, 0, 0); ">Email</span>
		 <%= form.text_field :email %> 
	</label>
	<label class="input"> 
		<span style="color: rgb(0, 0, 0); ">Subject</span> 
		<%= form.text_field :subject %> 
	</label>
	<label class="input"> 
		<span style="color: rgb(0, 0, 0); ">Please enter your comments/questions</span> 
		<%= form.text_area :body, :class => 'comments_txtarea', :rows => 10 %> 
	</label>
	<div class="field">
		<%= recaptcha_tags :ajax => true  %>
	</div>
	<%= form.submit "Send", :class => "action_button"%>
<% end %>

app/views/contact/create.js.erb
$("#flash_notice").remove();
$(".err_msgs").before('<div id="flash_notice"><%= escape_javascript(flash.delete(:notice)) %></div>');
$(".err_msgs").html("<%= escape_javascript render("shared/error_messages") %>");

app/views/contact/new.html.erb
<%= render "form", :object => @message %>

app/views/games/index.html.erb
<center><h4>Enjoy this tic-tac-toe game built in jQuery</h4></center>
<table border="0px" align="center">
<tr><td>
<div id="menu"></div>
<div id="board"></div>
</td></tr>
</table>

<%= label_tag 'Reset', nil, :class => 'reset' %>

app/views/home/index.html.erb
<h2 class="trigger"><%= link_to 'About Me', '#' %></h2>
<div class="toggle_container">
<div id="interest" class="toggle_block">
  <p>Hello There. Thank you for taking the time to look at my site. My main hobbies are computers, be it learning computer languages 
    or tinkering with some hardware, basketball, and reading.  You can either catch me at Barnes Nobles either reading or 
    messing with my computer or you can catch me at the park playing basketball. </p>
</div>
</div>

<h2 class="trigger"><%= link_to 'Education', '#' %></h2>
<div class="toggle_container">
<div id="education" class="toggle_block">
  <p>I graduated from Texas State with a Bachelor of Science in Computer Science with a minor in Mathamatics back in 2007</p>
</div>
</div>

<h2 class="trigger"><%= link_to 'Jobs', '#' %></h2>
<div class="toggle_container">
<div id="jobs" class="toggle_block">
  <ul class="jobs">
      <li><h4><%= link_to 'Neubus', 'http://www.neubus.com', :target => "_blank" %>(2006 - 2010)</h4>
      <p>I started as an intern and then was hired as a Software Developer once I graduated. As a Software Developer, I was in 
      charge of creating new applications, debugging current applications and providing technical support to many state agencies. </p>
    </li>
    <li><h4><%= link_to 'Pervasive', 'http://www.pervasive.com', :target => "_blank" %>(2010 - Present)</h4>
      <p>At Pervasive, I am a Web Developer who currently works on DNN. I design modules written in C# to be used through out the company's
      websites. I implement Jquery, HTML and CSS changes as well to current websites on a daily basis. I've worked with Database migrations
      involving data from a Drupal site to a DNN site.</p><p> Some of the websites I mainly work on are:
      <ul>
        <li><%= link_to 'Solutions', 'http://www.pervasive.com/solutions', :target => "_blank", :class => 'screenshot',
            :rel => '../images/solutions.png', :title => 'My primary focus at Pervasive' %></li>
        <li><%= link_to 'Galaxy', 'http://www.pervasive.com/galaxy', :target => "_blank", :class => 'screenshot',
            :rel => '../images/galaxy.png', :title => 'Check out Galaxy!!'%></li>
        <li><%= link_to 'Tools', 'http://www.pervasive.com/tools', :target => "_blank", :class => 'screenshot' ,
            :rel => '../images/tools.png' %></li>
      </ul></p>
    </li>
  </ul>
</div>
</div>

<h2 class="trigger"><%= link_to 'Projects', '#' %></h2>
<div class="toggle_container">
<div id="projects" class="toggle_block">
  
</div>
  
  
</div>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <p>
    Copyright © 2011. All rights reserved. 
    <%= build_link %>
  </p></footer>

app/views/layouts/_header.html.erb
<div class="main_menu">
<header id="header">
  <h1>
    <span>A personal portfolio with my resume, blogs, and other info</span>
  </h1>
</header>
  <nav id="nav">
  	<div id="nav_menu">
	    <ul>
	      <li><%= link_to "Home", home_path %></li>
	      <li><%= link_to "Austin", '#' %></li>   
	      <li><%= link_to "Tumblr", '#' %></li>  
	      <li><%= link_to "Games", games_path %></li>
	    </ul>
    </div>
  </nav>
 </div>

app/views/layouts/_sidebar.html.erb
<div class="block">
  <h3>
  	<%= link_to "Contact Me", contact_path %>
  </h3>
  <p>Bonjour! I'm Eddie.</p>
  <div id="me">
  <%= link_to gravatar_for("eddielopezzzz@hotmail.com", :size => 30)%>
  </div>
</div>
<div class="block">
  <h3>Programming Languages</h3>
  <ul id="skills">
    <li>C#/C++</li>
    <li>PHP</li>
    <li>Ruby</li>
    <li>Java</li>
    <li>Bash scripting</li>
    <li>Objective C#</li>
  </ul>
</div>
<div class="block">
  <h3>Web Stuff</h3>
  <ul id="web_frameworks">
    <li>ASP.NET</li>
    <li>Rails</li>
    <li>Jquery/JavaScript</li>
    <li>HTML 5</li>
  </ul>
</div>
<div class="block">
  <h3>CMS</h3>
  <ul id="db_lang">
    <li>DNN</li>
    <li>Wordpress</li>
  </ul>
</div>
<div class="block">
  <h3>Database Languages</h3>
  <ul id="db_lang">
    <li>MS SQL</li>
    <li>MYSQL</li>
    <li>Postgres</li>
    <li>SQLite</li>
  </ul>
</div>
<div class="block">
  <h3>Other Projects</h3>
  <ul id="other_projects">
    <li>Windows Phone 7 development</li>
    <li>iPhone Development</li>
    <li>Android</li>
  </ul>
</div>
<div class="block">
  <h3>Interests</h3>
  <ul id="interest">
    <li>Family/Friends</li>
    <li>Basketball</li>
    <li>Reading</li>
    <li>Girls... hehe</li>
  </ul>
</div>

app/views/layouts/_social.html.erb
<div id="ShareSidebar">
  <%= facebook_like %>
  <div class="social_stuff">
    <%= link_to "Share", "http://www.facebook.com/sharer.php", :name=> "fb_share", :type => "box_count"%>
    <script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script>
  </div>
  <div class="social_stuff">
    <script type="text/javascript" src="http://apis.google.com/js/plusone.js"></script>
    <g:plusone size="tall"></g:plusone>
  </div>
  <div class="social_stuff">
    <%= link_to "Tweet", "http://twitter.com/share", :class=> "twitter-share-button"%>
    <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script></script>
  </div>

  <div class="social_stuff">
    <script src="http://www.stumbleupon.com/hostedbadge.php?s=5"></script>
  </div>
  <div class="social_stuff_more">
    <script type="text/javascript" src="http://platform.linkedin.com/in.js"></script>
    <script type="in/share" data-counter="top"></script>
    <script type="IN/MemberProfile" data-id="http://www.linkedin.com/in/eddielopezzzz" data-format="hover" data-text="Eduardo Lopez"></script>
  </div>		
</div>

app/views/layouts/_stylesheets.html.erb
 <!--[if lt IE 9]>
 <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
 <![endif]-->
 
 <%= stylesheet_link_tag 'style' %>
 <%= stylesheet_link_tag 'social' %>
 <%= stylesheet_link_tag 'placeholder'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <%= render 'layouts/header' %>
    <div id="wrapper">
      <div id="content">
        <section class="round">
          <%= yield %>
        </section>
      </div>
      <div id="sidebar">
        <%= render 'layouts/sidebar' %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </div>
  <%= render 'layouts/social' %>
</body>
</html>

app/views/notifier/new_message.html.erb
<h1>You have just received an email from your site</h1>

<p>
Name: <%= @message.name %>
</p>

<p>
Email: <%= @message.email %>
</p>

<p>
Subject: <%= @message.subject %>
</p>

<p>
Body: <%= @message.body %>
</p>

app/views/notifier/new_message.text.erb
Name: <%= @message.name %>

Email: <%= @message.email %>

Subject: <%= @message.subject %>

Body: <%= @message.body %>

app/views/shared/_error_messages.html.erb
<% if @message.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@message.errors.count, "error")%> prohibited this 
		<%= @message.class.to_s.underscore.humanize.downcase %> from being saved:</h2>
	<ul>
		<% @message.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>